DROP TABLE LOOKUP_COUNTRY;
DROP TABLE LOOKUP_ETHNIC;
DROP TABLE LOOKUP_EVENT_CODES;
DROP TABLE LOOKUP_KNOWN_GROUPS;
DROP TABLE LOOKUP_RELIGION;
DROP TABLE LOOKUP_TYPE;
DROP TABLE LOOKUP_GOLDSTEIN_SCALE;

CREATE TABLE LOOKUP_COUNTRY (
 Code varchar(3),
 Label varchar(255)
);

CREATE TABLE LOOKUP_ETHNIC (
 Code varchar(3),
 Label varchar(255)
);

CREATE TABLE LOOKUP_EVENT_CODES (
 Code varchar(4),
 Label varchar(500)
);

CREATE TABLE LOOKUP_KNOWN_GROUPS (
 Code varchar(3),
 Label varchar(255)
);

CREATE TABLE LOOKUP_RELIGION (
 Code varchar(3),
 Label varchar(255)
);

CREATE TABLE LOOKUP_TYPE (
 Code varchar(3),
 Label varchar(255)
);

CREATE TABLE LOOKUP_GOLDSTEIN_SCALE (
 Code int,
 Scale float
);

CREATE INDEX LookupCountryCode ON LOOKUP_COUNTRY (Code);
CREATE INDEX LookupEthnicCode ON LOOKUP_ETHNIC (Code);
CREATE INDEX LookupEventCode ON LOOKUP_EVENT_CODES (Code);
CREATE INDEX LookupKnownGroupsCode ON LOOKUP_KNOWN_GROUPS (Code);
CREATE INDEX LookupReligionCode ON LOOKUP_RELIGION (Code);
CREATE INDEX LookupTypeCode ON LOOKUP_TYPE (Code);
